[package]
name = "sudoku_solver"
version = "0.1.0"
authors = ["Stefan Andreas Baur <stefan_andreas.baur@daimler.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
